version: '3'
services:
  app:
    build: .
    volumes:
      - .:/go/src
      - .:${PWD}
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  db:
    build:
      context: .docker/postgres
    tty: true
    volumes:
      - .docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=encoder
    ports:
      - "5432:5432"